name: test
on:
  push:
    branches:
      - '*'

defaults:
  run:
    shell: sh

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: debian:testing
    steps:
    - uses: actions/checkout@v4
    - run: apt -y update
    - run: apt -y install g++-multilib clang libboost-dev make yasm wget python3 #xz-utils nasm
    - run: yasm --version
    - name: Install xed and nasm
      run: |
        git clone https://github.com/intelxed/xed.git
        cd xed
        ./mfile.py --shared --prefix=$HOME/local
        ./mfile.py --install

        NASM_VER=2.16.01
        wget https://www.nasm.us/pub/nasm/releasebuilds/${NASM_VER}/nasm-${NASM_VER}.tar.gz
        tar xvf nasm-${NASM_VER}.tar.gz
        cd nasm-${NASM_VER}
        ./configure --prefix=$HOME/local
        make -j$(nproc)
        make install

    - name: Add ~/bin to PATH
      run: echo "$HOME/bin" >> $GITHUB_PATH

    - name: Check versions
      run: |
        xed -version
        nasm -version

    - run: |
        make test
        make -C sample CXXFLAGS="-DXBYAK_NO_EXCEPTION"
        cd test
        make xed_test
        rm -rf jmp64
        env CXX=""clang++ -std=c++20"" make jmp64 && ./jmp64
